<?php defined( 'ABSPATH' ) || exit; if ( ! is_array( $definition ) || ! is_array( $element ) ) { return; } ?>
<div class="wrap mobishop-page-builder">
<?php if ( isset( $_GET['updated'] ) ) : ?><div class="notice notice-success is-dismissible"><p><?php esc_html_e( 'Similar Products saved successfully.', 'mobishop' ); ?></p></div><?php endif; ?>
<div class="mobishop-page-workspace mobishop-commerce-preview-workspace">
<aside class="mobishop-page-preview"><div class="mobishop-page-phone"><div id="mobishop-commerce-preview" class="mobishop-page-phone__screen mobishop-app-preview" data-preview-kind="related"></div></div><p><?php esc_html_e( 'Live mobile preview', 'mobishop' ); ?></p></aside>
<form class="mobishop-page-editor mobishop-commerce-preview-form" method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>"><input type="hidden" name="action" value="mobishop_save_similar_products"><?php wp_nonce_field( 'mobishop_save_similar_products', 'mobishop_similar_nonce' ); ?>
<div class="mobishop-page-toolbar"><strong><?php esc_html_e( 'Similar Products', 'mobishop' ); ?></strong><?php submit_button( __( 'Save Similar Products', 'mobishop' ), 'primary', 'submit', false ); ?></div>
<section class="mobishop-page-card is-open" data-element="related_products"><div class="mobishop-page-card__header"><div><span class="dashicons dashicons-products"></span><strong><?php esc_html_e( 'Related Products', 'mobishop' ); ?></strong></div><label class="mobishop-page-master-toggle"><input type="hidden" name="related[enabled]" value="0"><input type="checkbox" name="related[enabled]" value="1" <?php checked( ! empty( $element['enabled'] ) ); ?>><span><?php esc_html_e( 'Show', 'mobishop' ); ?></span></label></div><div class="mobishop-page-card__body"><div class="mobishop-page-fields">
<?php foreach ( $definition['fields'] as $field ) : $key=$field['key']; $value=$element['settings'][$key] ?? $field['default']; $name='related[settings]['.$key.']'; ?><div class="mobishop-page-field"><label><?php echo esc_html( $field['label'] ); ?></label>
<?php if ( 'checkbox' === $field['type'] ) : ?><label class="mobishop-page-toggle"><input type="hidden" name="<?php echo esc_attr($name); ?>" value="0"><input type="checkbox" name="<?php echo esc_attr($name); ?>" value="1" <?php checked(!empty($value)); ?>><b><?php esc_html_e('Show','mobishop'); ?></b></label>
<?php elseif ( 'select' === $field['type'] ) : ?><select name="<?php echo esc_attr($name); ?>"><?php foreach($field['options'] as $option=>$label): ?><option value="<?php echo esc_attr($option); ?>" <?php selected((string)$value,(string)$option); ?>><?php echo esc_html($label); ?></option><?php endforeach; ?></select>
<?php elseif ( 'color' === $field['type'] ) : ?><input type="color" name="<?php echo esc_attr($name); ?>" value="<?php echo esc_attr($value); ?>">
<?php elseif ( 'number' === $field['type'] ) : ?><input type="number" name="<?php echo esc_attr($name); ?>" min="<?php echo esc_attr((string)$field['min']); ?>" max="<?php echo esc_attr((string)$field['max']); ?>" step="<?php echo esc_attr((string)$field['step']); ?>" value="<?php echo esc_attr((string)$value); ?>">
<?php else : ?><input type="text" name="<?php echo esc_attr($name); ?>" value="<?php echo esc_attr((string)$value); ?>"><?php endif; ?></div><?php endforeach; ?>
</div></div></section></form></div></div>
