<?php
/** Push notification management screen. */
defined( 'ABSPATH' ) || exit;
?>
<div class="wrap kidia-push-page">
	<header class="kidia-push-hero"><div><span class="dashicons dashicons-megaphone"></span><div><h1><?php esc_html_e( 'Push Notifications', 'kidia-mobile-cms' ); ?></h1><p><?php esc_html_e( 'Compose offers, order alerts and re-engagement messages for your app customers.', 'kidia-mobile-cms' ); ?></p></div></div><span class="kidia-provider-status <?php echo $provider_connected ? 'is-connected' : ''; ?>"><?php echo esc_html( $provider_connected ? __( 'Provider connected', 'kidia-mobile-cms' ) : __( 'Provider setup required', 'kidia-mobile-cms' ) ); ?></span></header>
	<?php if ( isset( $_GET['push_sent'] ) ) : ?><div class="kidia-toast is-visible"><span class="dashicons dashicons-yes-alt"></span><?php esc_html_e( 'Notification saved and passed to the connected provider.', 'kidia-mobile-cms' ); ?></div><?php endif; ?>
	<div class="kidia-push-stats"><div><span class="dashicons dashicons-groups"></span><b><?php echo esc_html( (string) $subscribed_customers ); ?></b><small><?php esc_html_e( 'Subscribed customers', 'kidia-mobile-cms' ); ?></small></div><div><span class="dashicons dashicons-smartphone"></span><b><?php echo esc_html( (string) $registered_devices ); ?></b><small><?php esc_html_e( 'Registered devices', 'kidia-mobile-cms' ); ?></small></div><div><span class="dashicons dashicons-controls-forward"></span><b><?php echo esc_html( (string) count( $history ) ); ?></b><small><?php esc_html_e( 'Notifications recorded', 'kidia-mobile-cms' ); ?></small></div></div>
	<div class="kidia-push-workspace">
		<form class="kidia-push-compose" method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>">
			<input type="hidden" name="action" value="kidia_mobile_send_push_notification"><?php wp_nonce_field( 'kidia_mobile_send_push_notification', 'kidia_mobile_push_nonce' ); ?>
			<div class="kidia-push-compose__head"><div><span class="dashicons dashicons-paper-plane"></span><h2><?php esc_html_e( 'Compose Notification', 'kidia-mobile-cms' ); ?></h2></div><button class="button button-primary" type="submit"><?php esc_html_e( 'Send Notification', 'kidia-mobile-cms' ); ?></button></div>
			<div class="kidia-push-fields">
				<label><span><?php esc_html_e( 'Title', 'kidia-mobile-cms' ); ?></span><input type="text" name="push_title" maxlength="100" required data-push-title placeholder="<?php esc_attr_e( 'Flash sale today!', 'kidia-mobile-cms' ); ?>"></label>
				<label class="is-wide"><span><?php esc_html_e( 'Message', 'kidia-mobile-cms' ); ?></span><textarea name="push_message" maxlength="500" rows="5" required data-push-message placeholder="<?php esc_attr_e( 'Tell customers what is new and why they should open the app.', 'kidia-mobile-cms' ); ?>"></textarea></label>
				<label><span><?php esc_html_e( 'Audience', 'kidia-mobile-cms' ); ?></span><select name="push_audience"><option value="all"><?php esc_html_e( 'All devices', 'kidia-mobile-cms' ); ?></option><option value="customers"><?php esc_html_e( 'Signed-in customers', 'kidia-mobile-cms' ); ?></option><option value="guests"><?php esc_html_e( 'Guest shoppers', 'kidia-mobile-cms' ); ?></option></select></label>
				<label><span><?php esc_html_e( 'Open URL', 'kidia-mobile-cms' ); ?></span><input type="url" name="push_action_url" placeholder="https://"></label>
				<label class="is-wide"><span><?php esc_html_e( 'Image URL', 'kidia-mobile-cms' ); ?></span><input type="url" name="push_image_url" placeholder="https://"></label>
			</div>
		</form>
		<aside class="kidia-push-preview"><small><?php esc_html_e( 'Live preview', 'kidia-mobile-cms' ); ?></small><div class="kidia-push-phone"><div class="kidia-push-clock">9:41</div><div class="kidia-push-bubble"><span>W</span><div><b data-push-preview-title><?php esc_html_e( 'Your notification title', 'kidia-mobile-cms' ); ?></b><p data-push-preview-message><?php esc_html_e( 'Your message will appear here.', 'kidia-mobile-cms' ); ?></p></div><small><?php esc_html_e( 'now', 'kidia-mobile-cms' ); ?></small></div></div></aside>
	</div>
	<section class="kidia-push-history"><h2><?php esc_html_e( 'History', 'kidia-mobile-cms' ); ?></h2><?php if ( $history ) : ?><div><?php foreach ( $history as $item ) : ?><article><span class="dashicons dashicons-megaphone"></span><div><strong><?php echo esc_html( (string) ( $item['title'] ?? '' ) ); ?></strong><p><?php echo esc_html( (string) ( $item['message'] ?? '' ) ); ?></p></div><small><?php echo esc_html( wp_date( get_option( 'date_format' ) . ' ' . get_option( 'time_format' ), absint( $item['created_at'] ?? time() ) ) ); ?></small><em><?php echo esc_html( (string) ( $item['status'] ?? 'saved' ) ); ?></em></article><?php endforeach; ?></div><?php else : ?><div class="kidia-data-empty"><span class="dashicons dashicons-megaphone"></span><strong><?php esc_html_e( 'No notifications yet', 'kidia-mobile-cms' ); ?></strong></div><?php endif; ?></section>
</div>
