<?php defined( 'ABSPATH' ) || exit; ?>
<div class="wrap kidia-page-builder kidia-splash-builder">
	<header class="kidia-page-builder__heading"><h1><?php esc_html_e( 'Splash Screen', 'kidia-mobile-cms' ); ?></h1><p><?php esc_html_e( 'Control the screen shown when the application starts.', 'kidia-mobile-cms' ); ?></p></header>
	<?php if ( isset( $_GET['updated'] ) ) : ?><div class="notice notice-success is-dismissible"><p><?php esc_html_e( 'Splash Screen saved successfully.', 'kidia-mobile-cms' ); ?></p></div><?php endif; ?>
	<div class="kidia-page-workspace">
		<aside class="kidia-page-preview"><div class="kidia-page-phone"><div class="kidia-page-phone__speaker"></div><div id="kidia-splash-preview" class="kidia-page-phone__screen kidia-splash-preview"><img alt=""><strong></strong><span class="spinner is-active"></span></div></div><p><?php esc_html_e( 'Live mobile preview', 'kidia-mobile-cms' ); ?></p></aside>
		<form class="kidia-page-editor" method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>">
			<input type="hidden" name="action" value="kidia_mobile_save_splash_screen"><?php wp_nonce_field( 'kidia_mobile_save_splash_screen', 'kidia_mobile_splash_nonce' ); ?>
			<div class="kidia-page-toolbar"><strong><?php esc_html_e( 'Splash Screen', 'kidia-mobile-cms' ); ?></strong><?php submit_button( __( 'Save Splash Screen', 'kidia-mobile-cms' ), 'primary', 'submit', false ); ?></div>
			<section class="kidia-page-card is-open"><div class="kidia-page-card__header"><div><span class="dashicons dashicons-format-image"></span><strong><?php esc_html_e( 'Startup Screen', 'kidia-mobile-cms' ); ?></strong></div><label class="kidia-page-master-toggle"><input type="hidden" name="splash[enabled]" value="0"><input type="checkbox" name="splash[enabled]" value="1" <?php checked( ! empty( $settings['enabled'] ) ); ?>><span><?php esc_html_e( 'Show', 'kidia-mobile-cms' ); ?></span></label><button type="button" class="button kidia-page-expand" aria-expanded="true"><span class="dashicons dashicons-arrow-down-alt2"></span></button></div>
				<div class="kidia-page-card__body"><div class="kidia-page-fields">
					<div class="kidia-settings-section-title"><?php esc_html_e( 'Image Settings', 'kidia-mobile-cms' ); ?></div>
					<div class="kidia-page-field kidia-page-field--image"><label><?php esc_html_e( 'Logo / image', 'kidia-mobile-cms' ); ?></label><div class="kidia-page-media"><input class="kidia-page-media-url" type="url" name="splash[image_url]" value="<?php echo esc_attr( $settings['image_url'] ); ?>"><button type="button" class="button kidia-page-media-choose"><?php esc_html_e( 'Choose image', 'kidia-mobile-cms' ); ?></button></div></div>
					<?php foreach ( array( 'image_width' => 'Image width', 'image_height' => 'Image height' ) as $key => $label ) : ?><div class="kidia-page-field"><label><?php echo esc_html( $label ); ?></label><input type="number" min="40" max="320" name="splash[<?php echo esc_attr( $key ); ?>]" value="<?php echo esc_attr( (string) $settings[ $key ] ); ?>"></div><?php endforeach; ?>
					<div class="kidia-page-field"><label><?php esc_html_e( 'Image fit', 'kidia-mobile-cms' ); ?></label><select name="splash[image_fit]"><?php foreach ( array( 'contain' => 'Contain', 'cover' => 'Cover', 'fill' => 'Fill' ) as $value => $label ) : ?><option value="<?php echo esc_attr( $value ); ?>" <?php selected( $settings['image_fit'], $value ); ?>><?php echo esc_html( $label ); ?></option><?php endforeach; ?></select></div>
					<div class="kidia-page-field"><label><?php esc_html_e( 'Image shape', 'kidia-mobile-cms' ); ?></label><select name="splash[image_shape]"><?php foreach ( array( 'none' => 'Original', 'rounded' => 'Rounded', 'circle' => 'Circle' ) as $value => $label ) : ?><option value="<?php echo esc_attr( $value ); ?>" <?php selected( $settings['image_shape'], $value ); ?>><?php echo esc_html( $label ); ?></option><?php endforeach; ?></select></div>
					<div class="kidia-settings-section-title"><?php esc_html_e( 'Background & Timing', 'kidia-mobile-cms' ); ?></div>
					<?php foreach ( array( 'background_color' => 'Background color', 'background_color_end' => 'Gradient color' ) as $key => $label ) : ?><div class="kidia-page-field"><label><?php echo esc_html( $label ); ?></label><input type="color" name="splash[<?php echo esc_attr( $key ); ?>]" value="<?php echo esc_attr( $settings[ $key ] ); ?>"></div><?php endforeach; ?>
					<div class="kidia-page-field"><label><?php esc_html_e( 'Duration (milliseconds)', 'kidia-mobile-cms' ); ?></label><input type="number" min="500" max="10000" step="100" name="splash[duration_ms]" value="<?php echo esc_attr( (string) $settings['duration_ms'] ); ?>"></div>
					<div class="kidia-settings-section-title"><?php esc_html_e( 'Text & Loader', 'kidia-mobile-cms' ); ?></div>
					<div class="kidia-page-field"><label><?php esc_html_e( 'Store name', 'kidia-mobile-cms' ); ?></label><input type="text" name="splash[store_name]" value="<?php echo esc_attr( $settings['store_name'] ); ?>"></div>
					<?php foreach ( array( 'show_store_name' => 'Show store name', 'show_loader' => 'Show loader' ) as $key => $label ) : ?><div class="kidia-page-field"><label><?php echo esc_html( $label ); ?></label><label class="kidia-page-toggle"><input type="hidden" name="splash[<?php echo esc_attr( $key ); ?>]" value="0"><input type="checkbox" name="splash[<?php echo esc_attr( $key ); ?>]" value="1" <?php checked( ! empty( $settings[ $key ] ) ); ?>><b><?php esc_html_e( 'Show', 'kidia-mobile-cms' ); ?></b></label></div><?php endforeach; ?>
					<?php foreach ( array( 'text_color' => 'Text color', 'loader_color' => 'Loader color' ) as $key => $label ) : ?><div class="kidia-page-field"><label><?php echo esc_html( $label ); ?></label><input type="color" name="splash[<?php echo esc_attr( $key ); ?>]" value="<?php echo esc_attr( $settings[ $key ] ); ?>"></div><?php endforeach; ?>
				</div></div>
			</section>
		</form>
	</div>
</div>
