<?php
/** Central WooCommerce store data workspace. */
defined( 'ABSPATH' ) || exit;
$store_tabs = array(
	'products' => array( __( 'Products', 'kidia-mobile-cms' ), 'dashicons-products' ),
	'categories' => array( __( 'Categories', 'kidia-mobile-cms' ), 'dashicons-category' ),
	'discounts' => array( __( 'Discounts', 'kidia-mobile-cms' ), 'dashicons-tickets-alt' ),
	'customers' => array( __( 'Customers', 'kidia-mobile-cms' ), 'dashicons-groups' ),
	'orders' => array( __( 'Orders', 'kidia-mobile-cms' ), 'dashicons-cart' ),
	'reports' => array( __( 'Reports', 'kidia-mobile-cms' ), 'dashicons-chart-bar' ),
	'analytics' => array( __( 'Analytics', 'kidia-mobile-cms' ), 'dashicons-chart-line' ),
	'settings' => array( __( 'Settings', 'kidia-mobile-cms' ), 'dashicons-admin-generic' ),
);
$manage_urls = array(
	'products' => admin_url( 'edit.php?post_type=product' ), 'categories' => admin_url( 'edit-tags.php?taxonomy=product_cat&post_type=product' ),
	'discounts' => admin_url( 'edit.php?post_type=shop_coupon' ), 'customers' => admin_url( 'users.php?role=customer' ),
	'orders' => admin_url( 'edit.php?post_type=shop_order' ), 'reports' => admin_url( 'admin.php?page=wc-reports' ),
	'analytics' => admin_url( 'admin.php?page=wc-admin&path=/analytics/overview' ), 'settings' => admin_url( 'admin.php?page=wc-settings' ),
);
$tab_url = static fn( $tab, $source = null ) => add_query_arg(
	array( 'page' => 'kidia-mobile-store-data', 'store_tab' => $tab, 'store_source' => null === $source ? $store_source : $source ),
	admin_url( 'admin.php' )
);
$is_source_tab = in_array( $store_tab, array( 'customers', 'orders', 'reports', 'analytics' ), true );
$source_labels = array( 'all' => __( 'All', 'kidia-mobile-cms' ), 'website' => __( 'Website', 'kidia-mobile-cms' ), 'mobile' => __( 'Mobile App', 'kidia-mobile-cms' ) );
$order_revenue = array_sum( array_map( static fn( $order ) => (float) $order->get_total(), $orders ) );
?>
<div class="wrap kidia-data-page">
	<header class="kidia-data-hero"><div><span class="dashicons dashicons-database"></span><div><h1><?php esc_html_e( 'Store Data', 'kidia-mobile-cms' ); ?></h1><p><?php esc_html_e( 'Manage the live commerce data used by your website and mobile app.', 'kidia-mobile-cms' ); ?></p></div></div><a class="button button-primary" href="<?php echo esc_url( $manage_urls[ $store_tab ] ); ?>"><?php esc_html_e( 'Open full manager', 'kidia-mobile-cms' ); ?></a></header>
	<nav class="kidia-data-tabs"><?php foreach ( $store_tabs as $key => $item ) : ?><a class="<?php echo $key === $store_tab ? 'is-active' : ''; ?>" href="<?php echo esc_url( $tab_url( $key ) ); ?>"><span class="dashicons <?php echo esc_attr( $item[1] ); ?>"></span><?php echo esc_html( $item[0] ); ?><?php if ( isset( $counts[ $key ] ) ) : ?><b><?php echo esc_html( (string) $counts[ $key ] ); ?></b><?php endif; ?></a><?php endforeach; ?></nav>
	<section class="kidia-data-panel kidia-data-panel--<?php echo esc_attr( $store_tab ); ?>">
		<div class="kidia-data-panel__head"><div><h2><?php echo esc_html( $store_tabs[ $store_tab ][0] ); ?></h2><?php if ( $is_source_tab ) : ?><nav class="kidia-source-filter" aria-label="<?php esc_attr_e( 'Data source', 'kidia-mobile-cms' ); ?>"><?php foreach ( $source_labels as $key => $label ) : ?><a class="<?php echo $key === $store_source ? 'is-active' : ''; ?>" href="<?php echo esc_url( $tab_url( $store_tab, $key ) ); ?>"><?php echo esc_html( $label ); ?></a><?php endforeach; ?></nav><?php endif; ?></div><a class="button button-primary" href="<?php echo esc_url( $manage_urls[ $store_tab ] ); ?>"><span class="dashicons dashicons-edit"></span><?php esc_html_e( 'Manage', 'kidia-mobile-cms' ); ?></a></div>

		<?php if ( 'products' === $store_tab ) : ?>
			<div class="kidia-data-table-wrap"><table class="kidia-data-table"><thead><tr><th><?php esc_html_e( 'Product', 'kidia-mobile-cms' ); ?></th><th><?php esc_html_e( 'SKU', 'kidia-mobile-cms' ); ?></th><th><?php esc_html_e( 'Stock', 'kidia-mobile-cms' ); ?></th><th><?php esc_html_e( 'Price', 'kidia-mobile-cms' ); ?></th><th><?php esc_html_e( 'Status', 'kidia-mobile-cms' ); ?></th><th><?php esc_html_e( 'Actions', 'kidia-mobile-cms' ); ?></th></tr></thead><tbody><?php foreach ( $products as $product ) : $link = get_permalink( $product->get_id() ); ?><tr><td><div class="kidia-data-identity"><?php echo wp_kses_post( $product->get_image( 'thumbnail' ) ); ?><strong><?php echo esc_html( $product->get_name() ); ?></strong></div></td><td><code><?php echo esc_html( $product->get_sku() ?: '—' ); ?></code></td><td><span class="kidia-status"><?php echo esc_html( wc_get_stock_html( $product ) ? wp_strip_all_tags( wc_get_stock_html( $product ) ) : __( 'Not managed', 'kidia-mobile-cms' ) ); ?></span></td><td><?php echo wp_kses_post( $product->get_price_html() ); ?></td><td><?php echo esc_html( ucfirst( $product->get_status() ) ); ?></td><td><div class="kidia-row-actions"><a href="<?php echo esc_url( get_edit_post_link( $product->get_id() ) ); ?>"><?php esc_html_e( 'Edit', 'kidia-mobile-cms' ); ?></a><a href="<?php echo esc_url( $link ); ?>" target="_blank" rel="noopener"><?php esc_html_e( 'View', 'kidia-mobile-cms' ); ?></a><button type="button" data-copy-link="<?php echo esc_attr( $link ); ?>"><?php esc_html_e( 'Copy link', 'kidia-mobile-cms' ); ?></button></div></td></tr><?php endforeach; ?></tbody></table></div>
		<?php elseif ( 'orders' === $store_tab ) : ?>
			<div class="kidia-data-summary"><div><small><?php esc_html_e( 'Shown orders', 'kidia-mobile-cms' ); ?></small><b><?php echo esc_html( (string) count( $orders ) ); ?></b></div><div><small><?php esc_html_e( 'Shown revenue', 'kidia-mobile-cms' ); ?></small><b><?php echo wp_kses_post( function_exists( 'wc_price' ) ? wc_price( $order_revenue ) : (string) $order_revenue ); ?></b></div></div>
			<div class="kidia-order-list"><?php foreach ( $orders as $order ) : ?><article><div class="kidia-order-number"><span>#<?php echo esc_html( (string) $order->get_id() ); ?></span><small><?php echo esc_html( 'mobile' === $order->get_meta( '_kidia_order_source' ) ? __( 'Mobile App', 'kidia-mobile-cms' ) : __( 'Website', 'kidia-mobile-cms' ) ); ?></small></div><div><strong><?php echo esc_html( $order->get_formatted_billing_full_name() ?: __( 'Guest', 'kidia-mobile-cms' ) ); ?></strong><small><?php echo esc_html( $order->get_billing_email() ); ?></small></div><div><strong><?php echo wp_kses_post( $order->get_formatted_order_total() ); ?></strong><small><?php echo esc_html( $order->get_payment_method_title() ); ?></small></div><span class="kidia-status is-<?php echo esc_attr( $order->get_status() ); ?>"><?php echo esc_html( wc_get_order_status_name( $order->get_status() ) ); ?></span><a class="button" href="<?php echo esc_url( method_exists( $order, 'get_edit_order_url' ) ? $order->get_edit_order_url() : '#' ); ?>"><?php esc_html_e( 'Open', 'kidia-mobile-cms' ); ?></a></article><?php endforeach; ?></div>
		<?php elseif ( 'customers' === $store_tab ) : ?>
			<div class="kidia-customer-list"><?php foreach ( $customers as $customer ) : ?><article><?php echo get_avatar( $customer->ID, 44 ); ?><div><strong><?php echo esc_html( $customer->display_name ); ?></strong><small><?php echo esc_html( $customer->user_email ); ?></small></div><div><b><?php echo esc_html( function_exists( 'wc_get_customer_order_count' ) ? (string) wc_get_customer_order_count( $customer->ID ) : '0' ); ?></b><small><?php esc_html_e( 'Orders', 'kidia-mobile-cms' ); ?></small></div><div><b><?php echo wp_kses_post( function_exists( 'wc_price' ) && function_exists( 'wc_get_customer_total_spent' ) ? wc_price( wc_get_customer_total_spent( $customer->ID ) ) : '—' ); ?></b><small><?php esc_html_e( 'Total spent', 'kidia-mobile-cms' ); ?></small></div><a class="button" href="<?php echo esc_url( get_edit_user_link( $customer->ID ) ); ?>"><?php esc_html_e( 'Profile', 'kidia-mobile-cms' ); ?></a></article><?php endforeach; ?></div>
		<?php elseif ( 'categories' === $store_tab ) : ?>
			<div class="kidia-category-list"><?php if ( ! is_wp_error( $categories ) ) : foreach ( $categories as $category ) : $category_link = get_term_link( $category ); ?><article><span class="dashicons dashicons-category"></span><div><strong><?php echo esc_html( $category->name ); ?></strong><small><?php echo esc_html( sprintf( _n( '%d product', '%d products', $category->count, 'kidia-mobile-cms' ), $category->count ) ); ?></small></div><div class="kidia-row-actions"><a href="<?php echo esc_url( get_edit_term_link( $category->term_id, 'product_cat' ) ); ?>"><?php esc_html_e( 'Edit', 'kidia-mobile-cms' ); ?></a><?php if ( ! is_wp_error( $category_link ) ) : ?><button type="button" data-copy-link="<?php echo esc_attr( $category_link ); ?>"><?php esc_html_e( 'Copy link', 'kidia-mobile-cms' ); ?></button><?php endif; ?></div></article><?php endforeach; endif; ?></div>
		<?php elseif ( 'discounts' === $store_tab ) : ?>
			<div class="kidia-coupon-list"><?php foreach ( $coupons as $coupon_post ) : $coupon = class_exists( 'WC_Coupon' ) ? new WC_Coupon( $coupon_post->ID ) : null; ?><article><span class="dashicons dashicons-tickets-alt"></span><code><?php echo esc_html( $coupon_post->post_title ); ?></code><strong><?php echo esc_html( $coupon ? $coupon->get_amount() . ( 'percent' === $coupon->get_discount_type() ? '%' : ' ' . get_woocommerce_currency() ) : '' ); ?></strong><small><?php echo esc_html( $coupon && $coupon->get_date_expires() ? $coupon->get_date_expires()->date_i18n( get_option( 'date_format' ) ) : __( 'No expiry', 'kidia-mobile-cms' ) ); ?></small><div class="kidia-row-actions"><a href="<?php echo esc_url( get_edit_post_link( $coupon_post->ID ) ); ?>"><?php esc_html_e( 'Edit', 'kidia-mobile-cms' ); ?></a><button type="button" data-copy-text="<?php echo esc_attr( $coupon_post->post_title ); ?>"><?php esc_html_e( 'Copy code', 'kidia-mobile-cms' ); ?></button></div></article><?php endforeach; ?></div>
		<?php elseif ( in_array( $store_tab, array( 'reports', 'analytics' ), true ) ) : ?>
			<div class="kidia-insight-layout"><div class="kidia-data-summary"><div><small><?php esc_html_e( 'Orders in view', 'kidia-mobile-cms' ); ?></small><b><?php echo esc_html( (string) count( $orders ) ); ?></b></div><div><small><?php esc_html_e( 'Revenue in view', 'kidia-mobile-cms' ); ?></small><b><?php echo wp_kses_post( function_exists( 'wc_price' ) ? wc_price( $order_revenue ) : (string) $order_revenue ); ?></b></div><div><small><?php esc_html_e( 'Average order', 'kidia-mobile-cms' ); ?></small><b><?php echo wp_kses_post( function_exists( 'wc_price' ) ? wc_price( count( $orders ) ? $order_revenue / count( $orders ) : 0 ) : '—' ); ?></b></div></div><div class="kidia-insight-links"><?php foreach ( array( __( 'Revenue trends', 'kidia-mobile-cms' ), __( 'Order performance', 'kidia-mobile-cms' ), __( 'Product performance', 'kidia-mobile-cms' ), __( 'Customer insights', 'kidia-mobile-cms' ) ) as $label ) : ?><a href="<?php echo esc_url( $manage_urls[ $store_tab ] ); ?>"><span class="dashicons dashicons-chart-line"></span><strong><?php echo esc_html( $label ); ?></strong><span class="dashicons dashicons-arrow-left-alt2"></span></a><?php endforeach; ?></div></div>
		<?php else : ?>
			<div class="kidia-settings-list"><?php foreach ( array( __( 'General store settings', 'kidia-mobile-cms' ) => 'general', __( 'Payments', 'kidia-mobile-cms' ) => 'checkout', __( 'Shipping', 'kidia-mobile-cms' ) => 'shipping', __( 'Tax', 'kidia-mobile-cms' ) => 'tax', __( 'Emails', 'kidia-mobile-cms' ) => 'email' ) as $label => $settings_tab ) : ?><a href="<?php echo esc_url( add_query_arg( 'tab', $settings_tab, $manage_urls['settings'] ) ); ?>"><span class="dashicons dashicons-admin-generic"></span><strong><?php echo esc_html( $label ); ?></strong><span class="dashicons dashicons-arrow-left-alt2"></span></a><?php endforeach; ?></div>
		<?php endif; ?>
	</section>
</div>
