<?php
/** App Header schema. @package MobiShop */
defined( 'ABSPATH' ) || exit;

return array(
	'title'       => __( 'App Header', 'mobishop' ),
	'description' => __( 'PatPat-style home header with logo, store name and customer actions.', 'mobishop' ),
	'icon'        => 'dashicons-align-wide',
	'defaults'    => array(
		'logo_url'       => '',
		'title'          => '',
		'subtitle'       => '',
		'layout'         => 'center',
		'height'         => 64,
		'logo_height'    => 38,
		'show_search'    => true,
		'show_cart'      => true,
		'show_account'   => false,
		'title_color'    => '#1F2933',
		'icon_color'     => '#1F2933',
		'background_color' => '#FFFFFF',
		'search_style' => 'icon',
		'search_placeholder' => __( 'Search products', 'mobishop' ),
		'search_background' => '#F1F3F4',
		'search_text_color' => '#5F6368',
		'sticky' => true,
		'shadow' => 'subtle',
		'border_radius' => 0,
		'horizontal_padding' => 12,
		'icon_size' => 24,
		'icon_gap' => 4,
		'show_wishlist' => false,
		'search_height' => 40,
		'search_radius' => 14,
		'account_style' => 'icon',
		'show_account_label' => false,
		'account_label' => __( 'Account', 'mobishop' ),
	),
	'tabs' => array(
		array( 'id' => 'content', 'label' => __( 'Content', 'mobishop' ) ),
		array( 'id' => 'layout', 'label' => __( 'Layout', 'mobishop' ) ),
	),
	'fields' => array(
		array( 'key' => 'logo_url', 'label' => __( 'Logo', 'mobishop' ), 'type' => 'image', 'tab' => 'content', 'default' => '', 'full_width' => true ),
		array( 'key' => 'title', 'label' => __( 'Store name', 'mobishop' ), 'type' => 'text', 'tab' => 'content', 'default' => '', 'full_width' => true ),
		array( 'key' => 'subtitle', 'label' => __( 'Subtitle', 'mobishop' ), 'type' => 'text', 'tab' => 'content', 'default' => '', 'full_width' => true ),
		array( 'key' => 'layout', 'label' => __( 'Header layout', 'mobishop' ), 'type' => 'select', 'tab' => 'layout', 'default' => 'center', 'options' => array( 'center' => __( 'Centered logo', 'mobishop' ), 'start' => __( 'Logo at start', 'mobishop' ) ) ),
		array( 'key' => 'height', 'label' => __( 'Header height', 'mobishop' ), 'type' => 'number', 'tab' => 'layout', 'min' => 48, 'max' => 120, 'step' => 1, 'default' => 64 ),
		array( 'key' => 'logo_height', 'label' => __( 'Logo height', 'mobishop' ), 'type' => 'number', 'tab' => 'layout', 'min' => 20, 'max' => 80, 'step' => 1, 'default' => 38 ),
		array( 'key' => 'show_search', 'label' => __( 'Show search', 'mobishop' ), 'type' => 'checkbox', 'tab' => 'layout', 'default' => true ),
		array( 'key' => 'show_cart', 'label' => __( 'Show cart', 'mobishop' ), 'type' => 'checkbox', 'tab' => 'layout', 'default' => true ),
		array( 'key' => 'show_account', 'label' => __( 'Show account', 'mobishop' ), 'type' => 'checkbox', 'tab' => 'layout', 'default' => false ),
		array( 'key' => 'title_color', 'label' => __( 'Title color', 'mobishop' ), 'type' => 'color', 'tab' => 'layout', 'default' => '#1F2933' ),
		array( 'key' => 'icon_color', 'label' => __( 'Icon color', 'mobishop' ), 'type' => 'color', 'tab' => 'layout', 'default' => '#1F2933' ),
		array( 'key' => 'background_color', 'label' => __( 'Background', 'mobishop' ), 'type' => 'color', 'tab' => 'layout', 'default' => '#FFFFFF' ),
		array( 'key' => 'sticky', 'label' => __( 'Sticky header', 'mobishop' ), 'type' => 'checkbox', 'tab' => 'layout', 'default' => true ),
		array( 'key' => 'shadow', 'label' => __( 'Shadow', 'mobishop' ), 'type' => 'select', 'tab' => 'layout', 'default' => 'subtle', 'options' => array( 'none' => __( 'None', 'mobishop' ), 'subtle' => __( 'Subtle', 'mobishop' ), 'strong' => __( 'Strong', 'mobishop' ) ) ),
		array( 'key' => 'icon_size', 'label' => __( 'Icon size', 'mobishop' ), 'type' => 'number', 'tab' => 'layout', 'min' => 16, 'max' => 40, 'default' => 24 ),
		array( 'key' => 'icon_gap', 'label' => __( 'Icon spacing', 'mobishop' ), 'type' => 'number', 'tab' => 'layout', 'min' => 0, 'max' => 24, 'default' => 4 ),
		array( 'key' => 'show_wishlist', 'label' => __( 'Show wishlist', 'mobishop' ), 'type' => 'checkbox', 'tab' => 'layout', 'default' => false ),
		array( 'key' => 'search_style', 'label' => __( 'Search style', 'mobishop' ), 'type' => 'select', 'tab' => 'layout', 'default' => 'icon', 'options' => array( 'icon' => __( 'Icon', 'mobishop' ), 'bar' => __( 'Search bar', 'mobishop' ) ) ),
		array( 'key' => 'search_placeholder', 'label' => __( 'Search placeholder', 'mobishop' ), 'type' => 'text', 'tab' => 'layout', 'default' => __( 'Search products', 'mobishop' ) ),
		array( 'key' => 'search_height', 'label' => __( 'Search height', 'mobishop' ), 'type' => 'number', 'tab' => 'layout', 'min' => 32, 'max' => 64, 'default' => 40 ),
		array( 'key' => 'search_radius', 'label' => __( 'Search radius', 'mobishop' ), 'type' => 'number', 'tab' => 'layout', 'min' => 0, 'max' => 32, 'default' => 14 ),
		array( 'key' => 'account_style', 'label' => __( 'Account style', 'mobishop' ), 'type' => 'select', 'tab' => 'layout', 'default' => 'icon', 'options' => array( 'icon' => __( 'Outline icon', 'mobishop' ), 'filled' => __( 'Filled icon', 'mobishop' ), 'avatar' => __( 'Avatar', 'mobishop' ) ) ),
		array( 'key' => 'account_label', 'label' => __( 'Account label', 'mobishop' ), 'type' => 'text', 'tab' => 'layout', 'default' => __( 'Account', 'mobishop' ) ),
		array( 'key' => 'show_account_label', 'label' => __( 'Show account label', 'mobishop' ), 'type' => 'checkbox', 'tab' => 'layout', 'default' => false ),
	),
);
