<?php
/** Product Grid schema. @package MobiShop */
defined( 'ABSPATH' ) || exit;

return array(
	'title'       => __( 'Product Grid', 'mobishop' ),
	'description' => __( 'Display WooCommerce products in a responsive mobile grid.', 'mobishop' ),
	'icon'        => 'dashicons-grid-view',
	'defaults'    => array(
		'title' => '', 'subtitle' => '', 'source' => 'latest', 'limit' => 8,
		'columns' => 2, 'category_id' => 0, 'product_ids' => '',
		'show_view_all' => true, 'view_all_label' => '', 'action_type' => '', 'action_value' => '',
		'card_style' => 'outlined', 'image_ratio' => 1, 'card_radius' => 20, 'enable_image_swipe' => false,
		'show_name' => true, 'show_price' => true, 'show_regular_price' => true,
		'show_badge' => true, 'show_rating' => false,
		'quick_add_enabled' => true,
		'quick_add_icon_variant' => 'bag', 'quick_add_icon_style' => 'outline', 'quick_add_icon_size' => 22,
		'quick_add_icon_color' => '#1F2933', 'quick_add_show_background' => true,
		'quick_add_background_color' => '#FFFFFF', 'quick_add_background_size' => 40, 'quick_add_radius' => 24,
		'quick_add_position' => 'bottom_end',
		'show_wishlist' => false, 'product_wishlist_icon_variant' => 'heart', 'product_wishlist_icon_style' => 'outline',
		'product_wishlist_icon_size' => 20, 'product_wishlist_icon_color' => '#1F2933',
		'product_wishlist_show_background' => true, 'product_wishlist_background_color' => '#FFFFFF',
		'product_wishlist_background_size' => 40, 'product_wishlist_radius' => 24,
		'product_wishlist_position' => 'top_end',
	),
	'fields'      => array(
		array( 'key' => 'title', 'label' => __( 'Section title', 'mobishop' ), 'type' => 'text', 'default' => '' ),
		array( 'key' => 'subtitle', 'label' => __( 'Subtitle', 'mobishop' ), 'type' => 'text', 'default' => '' ),
		array( 'key' => 'source', 'type' => 'select', 'default' => 'latest' ),
		array( 'key' => 'columns', 'type' => 'number', 'default' => 2, 'min' => 1, 'max' => 4 ),
		array( 'key' => 'limit', 'type' => 'number', 'default' => 8, 'min' => 1, 'max' => 50 ),
		array( 'key' => 'category_id', 'label' => __( 'Category ID', 'mobishop' ), 'type' => 'number', 'default' => 0, 'min' => 0 ),
		array( 'key' => 'product_ids', 'label' => __( 'Manual product IDs', 'mobishop' ), 'type' => 'text', 'default' => '' ),
		array( 'key' => 'card_style', 'label' => __( 'Card style', 'mobishop' ), 'type' => 'select', 'default' => 'outlined', 'options' => array( 'minimal' => __( 'Minimal', 'mobishop' ), 'no_shadow' => __( 'No shadow', 'mobishop' ), 'outlined' => __( 'Outlined', 'mobishop' ), 'elevated' => __( 'Elevated', 'mobishop' ) ) ),
		array( 'key' => 'image_ratio', 'label' => __( 'Image ratio', 'mobishop' ), 'type' => 'number', 'default' => 1, 'min' => 0.6, 'max' => 1.8, 'step' => 0.05 ),
		array( 'key' => 'enable_image_swipe', 'label' => __( 'Swipe product images on the card', 'mobishop' ), 'type' => 'checkbox', 'default' => false ),
		array( 'key' => 'card_radius', 'label' => __( 'Card radius', 'mobishop' ), 'type' => 'number', 'default' => 20, 'min' => 0, 'max' => 40 ),
		array( 'key' => 'show_view_all', 'label' => __( 'Show view all', 'mobishop' ), 'type' => 'checkbox', 'default' => true ),
		array( 'key' => 'show_name', 'label' => __( 'Show product name', 'mobishop' ), 'type' => 'checkbox', 'default' => true ),
		array( 'key' => 'show_price', 'label' => __( 'Show price', 'mobishop' ), 'type' => 'checkbox', 'default' => true ),
		array( 'key' => 'show_regular_price', 'label' => __( 'Show regular price', 'mobishop' ), 'type' => 'checkbox', 'default' => true ),
		array( 'key' => 'show_badge', 'label' => __( 'Show sale badge', 'mobishop' ), 'type' => 'checkbox', 'default' => true ),
		array( 'key' => 'show_rating', 'label' => __( 'Show rating', 'mobishop' ), 'type' => 'checkbox', 'default' => false ),
		array( 'key' => 'quick_add_enabled', 'label' => __( 'Quick add to cart', 'mobishop' ), 'type' => 'checkbox', 'default' => true ),
		array( 'key' => 'quick_add_icon_variant', 'label' => __( 'Quick add icon shape', 'mobishop' ), 'type' => 'select', 'default' => 'bag', 'options' => array( 'bag' => __( 'Shopping bag', 'mobishop' ), 'cart' => __( 'Shopping cart', 'mobishop' ), 'basket' => __( 'Shopping basket', 'mobishop' ) ) ),
		array( 'key' => 'quick_add_icon_style', 'label' => __( 'Quick add icon style', 'mobishop' ), 'type' => 'select', 'default' => 'outline', 'options' => array( 'outline' => __( 'Outline', 'mobishop' ), 'filled' => __( 'Filled', 'mobishop' ), 'rounded' => __( 'Rounded', 'mobishop' ) ) ),
		array( 'key' => 'quick_add_icon_size', 'label' => __( 'Quick add icon size', 'mobishop' ), 'type' => 'number', 'default' => 22, 'min' => 10, 'max' => 36 ),
		array( 'key' => 'quick_add_icon_color', 'label' => __( 'Quick add icon color', 'mobishop' ), 'type' => 'color', 'default' => '#1F2933' ),
		array( 'key' => 'quick_add_show_background', 'label' => __( 'White background behind icon', 'mobishop' ), 'type' => 'checkbox', 'default' => true ),
		array( 'key' => 'quick_add_background_color', 'label' => __( 'Quick add background color', 'mobishop' ), 'type' => 'color', 'default' => '#FFFFFF' ),
		array( 'key' => 'quick_add_background_size', 'label' => __( 'Quick add background size', 'mobishop' ), 'type' => 'number', 'default' => 40, 'min' => 10, 'max' => 64 ),
		array( 'key' => 'quick_add_radius', 'label' => __( 'Quick add background radius', 'mobishop' ), 'type' => 'number', 'default' => 24, 'min' => 0, 'max' => 40 ),
		array( 'key' => 'quick_add_position', 'label' => __( 'Quick add position', 'mobishop' ), 'type' => 'select', 'default' => 'bottom_end', 'options' => array( 'top_start' => 'Top start', 'top_end' => 'Top end', 'bottom_start' => 'Bottom start', 'bottom_end' => 'Bottom end' ) ),
		array( 'key' => 'show_wishlist', 'label' => __( 'Product wishlist icon', 'mobishop' ), 'type' => 'checkbox', 'default' => false ),
		array( 'key' => 'product_wishlist_icon_variant', 'label' => __( 'Product wishlist icon shape', 'mobishop' ), 'type' => 'select', 'default' => 'heart', 'options' => array( 'heart' => __( 'Heart', 'mobishop' ), 'rounded' => __( 'Rounded heart', 'mobishop' ), 'bookmark' => __( 'Bookmark', 'mobishop' ) ) ),
		array( 'key' => 'product_wishlist_icon_style', 'label' => __( 'Product wishlist icon style', 'mobishop' ), 'type' => 'select', 'default' => 'outline', 'options' => array( 'outline' => __( 'Outline', 'mobishop' ), 'filled' => __( 'Filled', 'mobishop' ) ) ),
		array( 'key' => 'product_wishlist_icon_size', 'label' => __( 'Product wishlist icon size', 'mobishop' ), 'type' => 'number', 'default' => 20, 'min' => 10, 'max' => 36 ),
		array( 'key' => 'product_wishlist_icon_color', 'label' => __( 'Product wishlist icon color', 'mobishop' ), 'type' => 'color', 'default' => '#1F2933' ),
		array( 'key' => 'product_wishlist_show_background', 'label' => __( 'Product wishlist background', 'mobishop' ), 'type' => 'checkbox', 'default' => true ),
		array( 'key' => 'product_wishlist_background_color', 'label' => __( 'Product wishlist background color', 'mobishop' ), 'type' => 'color', 'default' => '#FFFFFF' ),
		array( 'key' => 'product_wishlist_background_size', 'label' => __( 'Product wishlist background size', 'mobishop' ), 'type' => 'number', 'default' => 40, 'min' => 20, 'max' => 64 ),
		array( 'key' => 'product_wishlist_radius', 'label' => __( 'Product wishlist background radius', 'mobishop' ), 'type' => 'number', 'default' => 24, 'min' => 0, 'max' => 40 ),
		array( 'key' => 'product_wishlist_position', 'label' => __( 'Product wishlist position', 'mobishop' ), 'type' => 'select', 'default' => 'top_end', 'options' => array( 'top_start' => 'Top start', 'top_end' => 'Top end', 'bottom_start' => 'Bottom start', 'bottom_end' => 'Bottom end' ) ),
	),
);
